set(CMAKE_SYSTEM_NAME Linux)
set(CMAKE_SYSTEM_PROCESSOR x86_64)
set(TC_DIR "/home/clark/.local/toolchains/x86_64-linux-musl-cross")
set(CMAKE_CXX_KNOWN_FEATURES ON)
set(CMAKE_C_KNOWN_FEATURES ON)
set(CMAKE_SYSROOT ${TC_DIR}/x86_64-linux-musl/)

set(CMAKE_C_COMPILER ${TC_DIR}/bin/x86_64-linux-musl-gcc)
set(CMAKE_CXX_COMPILER ${TC_DIR}/bin/x86_64-linux-musl-g++)


set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)